#!/usr/bin/env bash
# a Bash script that uses ssh to connect to your server
# using the private key ~/.ssh/school with the user ubuntu.
# Only use ssh single-character flags
# You cannot use -l
ssh ubuntu@54.89.195.49 -i ~/.ssh/school
