#!/usr/bin/env bash
# a Bash script that uses ssh to connect to your server
# using the private key ~/.ssh/school with the user ubuntu.
# Only use ssh single-character flags
# You cannot use -l
ssh -l ~/.ssh/school ubuntu@34.203.201.7
